/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.ArquivoOutCarro;
import br.cesjf.lpiu.modelo.Automovel;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tassio
 */
public class CadCarro extends javax.swing.JFrame {

    private ArquivoInCarro arqin = new ArquivoInCarro();
    private Automovel car = null;
    int linha;
    private ArquivoOutCarro arqout = new ArquivoOutCarro();

    /**
     * Creates new form CadCarro
     */
    public CadCarro() {
        initComponents();
        auto = new Automovel();
        try {
            arqout.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public Automovel auto = null;

    public void limpar() {
        txtPlaca.setText("");
        txtModelo.setText("");
        txtData.setText("");
        txtValorBasico.setText("");
        comboMotorizacao.setSelectedIndex(-1);
        txtAliquota.setText("");
        txtImposto.setText("");
        txtValorBasico.setText("");
        txtValorTotal.setText("");
        btTipoCarro.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTipoCarro = new javax.swing.ButtonGroup();
        btLimpar = new javax.swing.JButton();
        rbCarga = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboMotorizacao = new javax.swing.JComboBox<>();
        jbAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAliquota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbUtilitario = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtImposto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbPasseio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtValorBasico = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JFormattedTextField();
        btCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCarro = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 90, 40));

        btTipoCarro.add(rbCarga);
        rbCarga.setText("Carga");
        getContentPane().add(rbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel1.setText("Placa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtValorTotal.setEnabled(false);
        getContentPane().add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 160, -1));

        jLabel10.setText("Dados do Automovel");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        comboMotorizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.4", "1.6", "1.8", "2.0" }));
        comboMotorizacao.setSelectedIndex(-1);
        comboMotorizacao.setToolTipText("");
        comboMotorizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMotorizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(comboMotorizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 108, 116, -1));

        jbAdd.setText("Adicionar");
        jbAdd.setEnabled(false);
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 90, 40));

        jLabel3.setText("Data de fabricação");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, -1));
        getContentPane().add(txtAliquota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 304, 130, -1));

        jLabel7.setText("Aliquota de imposto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 282, 130, -1));

        jLabel2.setText("Modelo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 20));

        jLabel8.setText("Imposto a pagar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel5.setText("Valor Basico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 86, -1, -1));

        btTipoCarro.add(rbUtilitario);
        rbUtilitario.setText("Utilitario");
        getContentPane().add(rbUtilitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel6.setText("Categoria");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtImposto.setEnabled(false);
        getContentPane().add(txtImposto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 120, -1));

        jLabel9.setText("Valor total de compra");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        btTipoCarro.add(rbPasseio);
        rbPasseio.setText("Passeio");
        rbPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPasseioActionPerformed(evt);
            }
        });
        getContentPane().add(rbPasseio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setText("Motorizacao");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 86, -1, -1));
        getContentPane().add(txtValorBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 108, 150, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 177, 30));

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 98, -1));

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 80, 40));

        jtCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Data Fabricação", "Motorização", "Valor Básico", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCarro.getTableHeader().setReorderingAllowed(false);
        jtCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCarro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 460, 140));

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 90, 40));

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 90, 40));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void comboMotorizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMotorizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMotorizacaoActionPerformed

    private void rbPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPasseioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPasseioActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

        Double valorBasico = Double.parseDouble(txtValorBasico.getText());
        Double aliquota = Double.parseDouble(txtAliquota.getText());

        Double imposto = auto.calcularImposto(valorBasico, aliquota);
        txtImposto.setText(imposto.toString());

        txtValorTotal.setText(String.valueOf(auto.calcularValorTotal(valorBasico, imposto)));

        jbAdd.setEnabled(true);

    }//GEN-LAST:event_btCalcularActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        
        auto = new Automovel();
        auto.setPlaca(txtPlaca.getText());
        auto.setModelo(txtModelo.getText());
        auto.setData(txtData.getText());
        auto.setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        auto.setMotorizacao((String) comboMotorizacao.getSelectedItem());

        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");

        auto.setCategoria(btTipoCarro.getSelection().getActionCommand());

        try {
            arqout.Adicionar(auto);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(
                null, "Carro Inserido com sucesso!");

        limpar();
        jbAdd.setEnabled(false);

        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarro.getModel();

        for (int i = jtCarro.getRowCount() - 1;
                i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0;
                i < listacar.size();
                i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }

    }//GEN-LAST:event_jbAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarro.getModel();

        for (int i = jtCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
    }//GEN-LAST:event_formWindowOpened

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        
        
        ArrayList<Automovel> listauto = new ArrayList<Automovel>();
        listauto = (ArrayList<Automovel>) arqin.getTodosCarros();

        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");

        listauto.get(linha).setPlaca(txtPlaca.getText());
        listauto.get(linha).setModelo(txtModelo.getText());
        listauto.get(linha).setData(txtData.getText());
        listauto.get(linha).setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        listauto.get(linha).setMotorizacao((String) comboMotorizacao.getSelectedItem());
        listauto.get(linha).setCategoria(btTipoCarro.getSelection().getActionCommand());
        
        try {
            arqout.recadastrar_todos(listauto);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!");

        limpar();

        DefaultTableModel modelo = (DefaultTableModel) jtCarro.getModel();

        if (jtCarro.getRowCount() > 0) {
            for (int i = jtCarro.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<Automovel> listauto2 = new ArrayList<Automovel>();
        listauto2 = arqin.getTodosCarros();

        for (int i = 0; i < listauto2.size(); i++) {
            modelo.addRow(listauto2.get(i).getcarro());
        }
        
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jtCarro.getModel();
        List<Automovel> list = new ArrayList<Automovel>();
        ArrayList<Automovel> nova_list = new ArrayList<Automovel>();
        linha = jtCarro.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 0);
        list = arqin.getTodosCarros();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPlaca().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Registro apagada com sucesso");

        limpar();
        
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);

    }//GEN-LAST:event_btExcluirActionPerformed

    private void jtCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarroMouseClicked

        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        linha = jtCarro.getSelectedRow();

        txtPlaca.setText(jtCarro.getValueAt(linha, 0).toString());
        txtModelo.setText(jtCarro.getValueAt(linha, 1).toString());
        txtData.setText(jtCarro.getValueAt(linha, 2).toString());

        String motorizacao = jtCarro.getValueAt(linha, 3).toString();

        switch (motorizacao) {
            case "1.0":
                comboMotorizacao.setSelectedIndex(0);
                break;
            case "1.4":
                comboMotorizacao.setSelectedIndex(1);
                break;
            case "1.6":
                comboMotorizacao.setSelectedIndex(2);
                break;
            case "1.8":
                comboMotorizacao.setSelectedIndex(3);
                break;
            case "2.0":
                comboMotorizacao.setSelectedIndex(4);
                break;
            default:
                comboMotorizacao.setSelectedIndex(-1);
                break;
        }

        txtValorBasico.setText(jtCarro.getValueAt(linha, 4).toString());

        String tipo = jtCarro.getValueAt(linha, 5).toString();

        if (tipo.equals("Carga")) {
            rbCarga.setSelected(true);
        } else if (tipo.equals("Passeio")) {
            rbPasseio.setSelected(true);
        } else {
            rbUtilitario.setSelected(true);
        }
    }//GEN-LAST:event_jtCarroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup btTipoCarro;
    private javax.swing.JComboBox<String> comboMotorizacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdd;
    private javax.swing.JTable jtCarro;
    private javax.swing.JRadioButton rbCarga;
    private javax.swing.JRadioButton rbPasseio;
    private javax.swing.JRadioButton rbUtilitario;
    private javax.swing.JTextField txtAliquota;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtImposto;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtPlaca;
    private javax.swing.JTextField txtValorBasico;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
