package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.ArquivoInCompra;
import br.cesjf.lpiu.arquivos.ArquivoInPessoa;
import br.cesjf.lpiu.arquivos.ArquivoOutCompra;
import br.cesjf.lpiu.modelo.Automovel;
import br.cesjf.lpiu.modelo.Compra;
import br.cesjf.lpiu.modelo.Pessoa;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author benfi
 */
public class CompraRealizada extends javax.swing.JFrame {

    private ArquivoInPessoa arqin = new ArquivoInPessoa();
    private Pessoa people = null;
   
    private ArquivoInCarro arqin2 = new ArquivoInCarro();
    private Automovel car = null;
    
    private ArquivoInCompra arqin3 = new ArquivoInCompra();
    private Compra compra = null;
    int linha;
    int linha2;
    private ArquivoOutCompra arqout3 = new ArquivoOutCompra();
    
    /**
     * Creates new form CompraRealizada
     */
    public CompraRealizada() {
        initComponents();
        compra = new Compra();
        try {
            arqout3.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CompraRealizada.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CompraRealizada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTCompra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPessoa = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTCarro = new javax.swing.JTable();
        btVincular = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pessoa", "RG", "Placa", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCompra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTCompra);

        jTPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTPessoa.getTableHeader().setReorderingAllowed(false);
        jTPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPessoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTPessoa);

        jTCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Placa", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCarro.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTCarro);

        btVincular.setText("Vincular");
        btVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVincularActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pessoas");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Carros");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecione uma pessoa na tabela Pessoas e uma carro na tabela Carros e click no botão vincular para relizar a compra.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addGap(334, 334, 334)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVincular, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVincular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVincularActionPerformed
        
        compra = new Compra();
        linha = jTPessoa.getSelectedRow();
        linha2 = jTCarro.getSelectedRow();
        
        compra.getPessoa().setNome(jTPessoa.getValueAt(linha, 0).toString());
        compra.getPessoa().setRg(jTPessoa.getValueAt(linha, 1).toString());
        
        compra.getAuto().setPlaca(jTCarro.getValueAt(linha2, 0).toString());
        compra.getAuto().setModelo(jTCarro.getValueAt(linha2, 1).toString());
        
        try {
            arqout3.Adicionar(compra);
        } catch (IOException ex) {
            Logger.getLogger(CompraRealizada.class
                .getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(
            null, "Compra vindulada com sucesso!");
      

        int cont = 1;

        List<Compra> listacompra = new ArrayList<Compra>();

        listacompra= arqin3.getTodasCompras();
        DefaultTableModel modelocompra = (DefaultTableModel) jTCompra.getModel();

        for (int i = jTCompra.getRowCount() - 1;
            i >= 0; --i) {
            modelocompra.removeRow(i);
        }

        for (int i = 0;
            i < listacompra.size();
            i++) {
            modelocompra.addRow(listacompra.get(i).getcompra());
            cont++;
        }
        
    }//GEN-LAST:event_btVincularActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosing

    private void jTPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPessoaMouseClicked

    }//GEN-LAST:event_jTPessoaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        int cont = 1;

        List<Pessoa> listapeople = new ArrayList<Pessoa>();

        listapeople = arqin.getTodasPessoas();
        DefaultTableModel modelopeople = (DefaultTableModel) jTPessoa.getModel();

        for (int i = jTPessoa.getRowCount() - 1;
                i >= 0; --i) {
            modelopeople.removeRow(i);
        }

        for (int i = 0;
                i < listapeople.size();
                i++) {
            modelopeople.addRow(listapeople.get(i).getpessoa());
            cont++;
        }
        
        int cont2 = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin2.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jTCarro.getModel();

        for (int i = jTCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
        
        int cont3 = 1;

        List<Compra> listacompra = new ArrayList<Compra>();

        listacompra = arqin3.getTodasCompras();
        DefaultTableModel modelocompra = (DefaultTableModel) jTCompra.getModel();

        for (int i = jTCompra.getRowCount() - 1; i >= 0; --i) {
            modelocompra.removeRow(i);
        }

        for (int i = 0; i < listacompra.size(); i++) {
            modelocompra.addRow(listacompra.get(i).getcompra());
            cont++;           
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) jTCompra.getModel();
        List<Compra> list = new ArrayList<Compra>();
        ArrayList<Compra> nova_list = new ArrayList<Compra>();
        linha = jTCompra.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 1);
        list = arqin3.getTodasCompras();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPessoa().getRg().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout3.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(CompraRealizada.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Compra apagada com sucesso");
        
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraRealizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraRealizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraRealizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraRealizada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraRealizada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVincular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTCarro;
    private javax.swing.JTable jTCompra;
    private javax.swing.JTable jTPessoa;
    // End of variables declaration//GEN-END:variables
}
